services:
  postgres_lakehouse:
    image: postgres:15-alpine
    container_name: postgres_lakehouse
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: